package com.example.ui

enum class Screen {
    AUTH,
    DASHBOARD,
    SEARCH,
    DOCUMENTS,
    FOLDER_CONTENT,
    DOCUMENT_DETAIL,
    UPLOAD_DOCUMENT,
    SHARE_DOCUMENT,
    DUPLICATE_FILES,
    TRASH,
    REPORTS,
    USERS_PERMISSIONS,
    BACKUP_SECURITY,
    EDIT_PROFILE,
    NOTIFICATIONS,
    AUDIT_LOG,
    CHATBOT,
    DOCUMENT_VIEWER
}
